site_name: One-Method-Of-Mangrove-Classification-Using-Machine-Learning

theme: Perceptron and Logistic regression


nav:
    Logistic regression is a discriminant model which learns the probability of belonging to each category under given characteristic conditions, namely p(y∣x)p(y∣x).
    The generative model learns the joint probability of features and categories namely p(x,y)p(x,y).

